// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { PlayersTable, PlayersTableData, PlayersTableTableId } from "./tables/PlayersTable.sol";
import { OffchainMessagesTable, OffchainMessagesTableData, OffchainMessagesTableTableId } from "./tables/OffchainMessagesTable.sol";
import { Counter, CounterTableId } from "./tables/Counter.sol";
