// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IMessagingSystem {
  function sendOffchainMessage(string memory message) external returns (address);
}
