// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { OffchainMessagesTableData } from "./../Tables.sol";

interface IMessagingSystem {
  function sendOffchainMessage(string memory message) external returns (OffchainMessagesTableData memory);
}
