// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

interface IPlayerSystem {
  function registerPlayer(string memory name) external;

  function registerPlayer() external;

  function unregisterPlayer() external;
}
